[addressbooks]
[[contacts]]
path = ~/.local/share/contacts/

[general]
default_action = list
editor = nvim
merge_editor = vimdiff

[contact table]
display = formatted_name
group_by_addressbook = no
reverse = no
show_nicknames = no
show_uids = no
sort = formatted_name
localize_dates = yes

[vcard]
private_objects = X-GOOGLE-ETAG,
search_in_source_files = yes
skip_unparsable = no
