#!/data/data/com.termux/files/usr/bin/bash
# Search all journal files with ripgrep and fzf

JOURNAL_DIR="$HOME/storage/shared/Dropbox/org/denote/journal"

if [[ -n "$1" ]]; then
    # Direct search
    rg -i "$1" "$JOURNAL_DIR" --color=always | less -R
else
    # Interactive search with fzf
    rg -l "" "$JOURNAL_DIR" | fzf --preview 'head -50 {}' --bind 'enter:execute(am start -a android.intent.action.VIEW -d "file://{}" -t "text/plain")'
fi
