;; Generated by theme engine. Do not edit.
(load-theme 'wombat t)
;; Reset buffer-id face so it inherits from mode-line instead of
;; clashing with dark backgrounds (e.g. deeper-blue sets it to blue4).
(set-face-attribute 'mode-line-buffer-id nil :foreground 'unspecified)
