;; Generated by theme engine. Do not edit.
(load-theme 'wheatgrass t)
(custom-set-faces
   '(mode-line ((t (:height 0.8))))
   '(mode-line-active ((t (:background "#2a3a2a" :box (:line-width 4 :color "#2a3a2a") :foreground "#b0c0b0"))))
   '(mode-line-inactive ((t (:background "#2a2520" :box (:line-width 4 :color "#2a2520") :foreground "#7a7060")))))
